config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#index'

  resources :rates
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def valid_attribute?(attribute_name)
    self.valid?
    self.errors[attribute_name].blank?
  end
end

app/models/rate.rb
# frozen_string_literal: true

class Rate < ApplicationRecord
  belongs_to :user

  default_scope { order(created_at: :desc) }

  validates :base_currency, presence: true
  validates :target_currency, presence: true
  validates :amount, presence: true,
                     format: { with: /\A\d+(?:\.\d{0,2})?\z/ }
  validates :weeks, presence: true,
                    numericality: { greater_than: 0, less_than_or_equal_to: 25 }

  AVAILABLE_CURRENCIES = %w[AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD
                            HRK HUF IDR ILS INR JPY KRW MXN MYR NOK NZD
                            PHP PLN RON RUB SEK SGD THB TRY USD ZAR].freeze
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :rates, dependent: :delete_all
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def home; end
end

app/controllers/rates_controller.rb
# frozen_string_literal: true

class RatesController < ApplicationController
  def index
    @rates = Rate.where(user_id: current_user.id)
  end

  def show
    @rate = Rate.find(params[:id])
    return render 'pages/index.html.erb' if !current_user.present? || current_user.id != @rate.user_id

    @result = ::Fixer::Service.new(@rate).calculate
  end

  def new
    @rate = Rate.new
  end

  def create
    @rate = Rate.new(base_currency: params[:base_currency],
                     target_currency: params[:target_currency],
                     amount: params[:rate][:amount],
                     weeks: params[:rate][:weeks],
                     user_id: current_user.id)
    if @rate.save
      redirect_to_home
    else
      render 'new'
    end
  end

  def edit
    @rate = Rate.find(params[:id])
    render 'pages/index.html.erb' if !current_user.present? || current_user.id != @rate.user_id
  end

  def update
    @rate = Rate.find(params[:id])
    @rate.update(base_currency: params[:base_currency],
                 target_currency: params[:target_currency],
                 amount: params[:rate][:amount],
                 weeks: params[:rate][:weeks],
                 user_id: current_user.id)
    redirect_to_home
  end

  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy
    redirect_to_home
  end

  def redirect_to_home
    path = rates_path
    redirect_to path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/rates_helper.rb
# frozen_string_literal: true

module RatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcane</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <% if current_user %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link home-full" href="/rates">Home <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <div class="main-menu-items">
        <span class="menu-item"> <%= current_user.name %></span>
        <%if current_user.image %>
        <%= image_tag((current_user.image), :class => "menu-img")  %>
        <%end %>
        <span class="menu-item home-mobile"> <%= link_to "Home", rates_path, :class => "home-mobile" %> </span>
        <span class="menu-item"> <%= link_to "Sign out", destroy_user_session_path, method: :delete , :class => "sign-out" %> </span>
      </div>
    </div>
  </nav>
    <% end %>



  <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
  <script type="text/javascript">
      window.location.href = "/rates"
  </script>
<% end %>
<div class="container">
  <div class="login-wrapper">

    <h2>Welcome to exchange rate app!</h2>

    <div class="sign-in-button-wrapper">
      <% unless current_user %>
        <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, :class => "btn btn-danger sign-in-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/rates/edit.html.erb
<div class="container">
  <div class="wrapper">
    <div class="header">
      <%= link_to fa_icon("arrow-left", :class => "icon back-btn"), rates_path %>
      <h2 class="edit-new-header">Edit your currencies and amount</h2>
    </div>
    <div class="form-wrapper">
    <%=form_for :rate, url: rate_path(@rate), method: :patch do |f| %>
      <% if @rate.errors.any? %>
        <% @rate.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
        <% end %>
      <% end %>
      <p>
        <%=f.label :base_currency %><br>
        <%= select_tag :base_currency, options_for_select(Rate::AVAILABLE_CURRENCIES,:selected =>@rate["base_currency"]), {:class => "form-control"} %>
      </p>
      <p>
        <%=f.label :target_currency %><br>
        <%= select_tag :target_currency, options_for_select(Rate::AVAILABLE_CURRENCIES, :selected =>@rate["target_currency"]), {:class => "form-control"} %>
      </p>
      <p>
        <%=f.label :amount %><br>
        <%=f.text_field :amount , {:class => "form-control"} %>
      </p>
        <p>
          <%= f.label :weeks %><br>
          <%= f.text_field :weeks, {:class => "form-control"} %>
        </p>

        <p class="submit-p">
        <%=f.submit 'SAVE' ,:class => "btn btn-success app-btn"  %>
      </p>
    <% end %>
    </div>
  </div>
</div>

app/views/rates/index.html.erb
<div class="container">
  <div class="wrapper">
    <h2>Welcome, <%= current_user.name %> !</h2>
    <br>

    <% if @rates.length < 1 %>
      <div class="no-rates rates-header">You have no exchange pairs created! Please create a new one.</div>
    <% end %>

    <% if @rates.length >= 1 %>
      <h4 class="rates-header">Your exchange rate pairs:</h4>
      <table class="table">
        <thead class="table-header">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Base</th>
          <th scope="col">Target</th>
          <th scope="col">Base amount</th>
          <th scope="col">Weeks</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
          <th scope="col">Calculations</th>
        </tr>
        </thead>
        <tbody>
        <% @rates.each_with_index do |item, index| %>

          <tr class="tableRow">
            <td>
              <span class="mobile-span">#</span>
              <span><%= index + 1 %></span>
            </td>
            <td>
              <span class="mobile-span">Base</span>
              <span><%= item["base_currency"] %></span>
            </td>
            <td>
              <span class="mobile-span">Target</span>
              <span><%= item["target_currency"] %></span>
            </td>
            <td>
              <span class="mobile-span">Base amount</span>
              <span><%= item["amount"] %></span>
            </td>
            <td>
              <span class="mobile-span">Weeks</span>
             <span><%= item["weeks"] %></span>
            </td>
            <td>
              <span class="mobile-span">Edit</span>
              <%=link_to  fa_icon("pencil",:class => "icon"), edit_rate_path(item["id"])%>
            </td>
            <td>
              <span class="mobile-span">Delete</span>
              <%=link_to  fa_icon("trash",:class => "icon"), rate_path(item["id"]), :method => :delete %>
            </td>
            <td>
              <span class="mobile-span">Calculations</span>
              <%=link_to  fa_icon("arrow-right",:class => "icon"), rate_path(item["id"])%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>

    <%= link_to "Add new pair", new_rate_path, :class => "btn btn-primary app-button" %>
  </div>
</div>

app/views/rates/new.html.erb
<div class="container">
  <div class="wrapper">
    <div class="header">
      <%= link_to fa_icon("arrow-left", :class => "icon back-btn"), rates_path %>
      <h2 class="edit-new-header">Please select your currencies and amount</h2>
    </div>
    <div class="form-wrapper">
      <%= form_for :rate, url: rates_path do |f| %>
      <% if @rate.errors.any? %>
        <% @rate.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
        <% end %>
      <% end %>
      <p>
        <%= f.label :base_currency %><br>
        <%= select_tag :base_currency, options_for_select(Rate::AVAILABLE_CURRENCIES), {:class => "form-control"} %>
      </p>
      <p>
        <%= f.label :target_currency %><br>
        <%= select_tag :target_currency, options_for_select(Rate::AVAILABLE_CURRENCIES), {:class => "form-control"} %>
      </p>
      <p>
        <%= f.label :amount %><br>
        <%= f.text_field :amount, placeholder: "Amount of base currency" , :class => "form-control" %>
      </p>

        <p>
          <%= f.label :weeks %><br>
          <%= f.text_field :weeks, placeholder: "Number of weeks to count", :class => "form-control" %>
        </p>

        <p class="submit-p">
        <%= f.submit 'SAVE', :class => "btn btn-success app-btn" %>
      </p>
    <% end %>
    </div>
  </div>
</div>

app/views/rates/show.html.erb
<div class="container">
  <div class="show-header">
    <%= link_to fa_icon("arrow-left", :class => "icon back-btn"), rates_path %>
    <h2><%= @rate.base_currency %> to <%= @rate.target_currency %> (amount : <%= @rate.amount %>)</h2>
  </div>
  <% if @result.success? %>
  <div class="show-wrapper">
    <table class="table">
      <thead class="table-header">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Date</th>
        <th scope="col">Week number</th>
        <th scope="col">Exchange rate</th>
        <th scope="col">Amount</th>
        <th scope="col">Profit/loss</th>
      </tr>
      </thead>
      <tbody>
      <% @result.response.each_with_index do |item, index| %>

        <tr class="tableRow">
          <% rate = item[:exchange_rate] %>
          <td>
            <span class="mobile-span">#</span>
            <span> <%= index + 1 %></span>
          </td>
          <td>
            <span class="mobile-span">Year</span>
            <span><%= item["date"] %></span></td>
          <td>
            <span class="mobile-span">Week number</span>
            <span><%= item[:week_nr] %></span>
          </td>
          <td class="<%= 'max-rate' if rate == @result.max_rate %>
                     <%= 'min-rate' if rate == @result.min_rate %>">
            <span class="mobile-span">Exchange rate</span>
            <span><%= number_with_precision(item[:exchange_rate], :precision => 4) %></span>
          </td>
           <td>
            <span class="mobile-span">Amount</span>
            <span><%= number_with_precision(item[:converted_amount], :precision => 4) %></span>
           </td>
          <td class="<%= item[:difference] > 0 ? 'profit' : 'loss' %>
                    <%= 'neutral' if rate== @result.today_rate %>">
            <span class="mobile-span">Profit/loss</span>
            <span> <%= rate== @result.today_rate ? "---" : number_with_precision(item[:difference], :precision => 4) %></span>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div style="margin-top: 30px"></div>
    <%= line_chart @result.chart_data%>
    <div style="margin-top: 30px"></div>
  </div>
    <% end %>
  <% unless @result.success? %>
  <div class="error-div"> Something went wrong,please check your currencies.</div>
  <% end %>
</div>